import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Container from "@/components/container/Container";
import HomePerson from "../assets/images/running-man.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className={styles.heading}>
          <div className={styles.heading_titles}>
            <h1>Daily</h1>
            <h2>Weather</h2>
          </div>

          <Image
            src={HomePerson}
            width={250}
            height={250}
            priority={true}
            alt="running man"
          />
        </div>
        <div className={styles.bottom_box}>
          <Image
            src={HomePerson}
            width={150}
            className={`${styles.home_pic_shadow}`}
            alt="running man shadow"
          />
        </div>
      </Container>
    </>
  );
}
